[package]
name = "sxn-chain-bridge"
authors = ["SafeXNetwork"]
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.4", default-features = false, features = ["derive"] }
